---
title: "paper"
author: "William Mullins"
format: 
  html:
    ouput-file: "paper.html"
---
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##                                 Background                               ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```{r}
#| include: false

#Install Required Packages
library(here)
library(janitor)
library(tidyverse)
library(lubridate)
library(patchwork)
library(hrbrthemes)
library(viridis)
library(paletteer)

# Load functions 
source("../functions/roll_mean.R")
source("../functions/weeks_since_start.R")
source("../functions/weeks_to_dates.R")
source("../functions/create_combined_graph.R")
```

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##                                    Data                                  ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```{r}
# Read in clean data
merged_data_frame <- read.csv(here::here("data", "clean_data.csv"))
merged_data_frame$date <-lubridate::as_date(merged_data_frame$date)

# View
head(merged_data_frame)

```

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##                                  Methods                                 ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```{r}
#P lotting the data
# Runs the testing file
merged_plots <- create_combined_graph() + plot_layout(axes = "collect", guides = "collect") & 
  theme(plot.margin = unit(c(0.1,0.1,0.1,0.1), "cm"), 
        axis.title.x = element_text(hjust = 0.5, size = 15))
```

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##                                  Results                                 ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```{r}
merged_plots 

ggsave(plot = merged_plots, here::here("figs", "merged_plots.jpg"), width = 6, height = 4)
```
